# Generated by Django 6.0.1 on 2026-03-21 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SettlementOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "output_id",
                    models.CharField(
                        help_text="sout_{uuid_v4}", max_length=50, unique=True
                    ),
                ),
                ("covenant_id", models.CharField(db_index=True, max_length=50)),
                (
                    "snapshot_id",
                    models.UUIDField(help_text="對應 ACR-20 的 TokenSnapshot ID"),
                ),
                ("calculation_id", models.UUIDField(default=uuid.uuid4)),
                ("total_tokens", models.PositiveIntegerField()),
                (
                    "owner_share_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "platform_share_pct",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("pool_share_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "distributions",
                    models.JSONField(help_text="儲存所有 Agent 的份額建議"),
                ),
                ("log_id", models.UUIDField(help_text="對應 ACR-300 的 log_id")),
                ("log_hash", models.CharField(max_length=64)),
                (
                    "chain_anchor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("disputed", "Disputed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="SettlementDispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raised_by", models.CharField(help_text="agent_id", max_length=50)),
                ("raised_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                (
                    "disputed_agent",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("resolution", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="settlement.settlementoutput",
                    ),
                ),
            ],
        ),
    ]
