# Generated by Django 6.0.1 on 2026-03-21 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("covenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grant_id",
                    models.CharField(
                        help_text="grant_{uuid_v4}", max_length=50, unique=True
                    ),
                ),
                ("covenant_id", models.CharField(db_index=True, max_length=50)),
                ("tier_id", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "platform_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="covenants.platformidentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
                "unique_together": {("covenant_id", "platform_identity", "tier_id")},
            },
        ),
    ]
