# Generated by Django 6.0.1 on 2026-03-21 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PendingToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("covenant_id", models.CharField(db_index=True, max_length=50)),
                ("agent_id", models.CharField(max_length=50)),
                ("draft_id", models.CharField(max_length=100, unique=True)),
                ("estimated_tokens", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="TokenLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("covenant_id", models.CharField(db_index=True, max_length=50)),
                ("agent_id", models.CharField(db_index=True, max_length=50)),
                ("delta", models.IntegerField(help_text="正數為增加，負數為撤銷")),
                ("balance_after", models.PositiveIntegerField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("passage", "段落貢獻"),
                            ("edit", "段落修改"),
                            ("bible", "世界觀設定"),
                            ("outline", "章節大綱"),
                            ("vote_reward", "投票獎勵"),
                            ("reversal", "撤銷"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(help_text="例如 draft_id", max_length=100),
                ),
                (
                    "log_id",
                    models.UUIDField(help_text="對應 ACR-300 的 log_id", unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("pending", "Pending"),
                            ("reversed", "Reversed"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["covenant_id", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("covenant_id", models.CharField(max_length=50, unique=True)),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                ("trigger_log_id", models.UUIDField()),
                ("total_tokens", models.PositiveIntegerField()),
                ("balances", models.JSONField(help_text="儲存所有 Agent 的份額快照")),
                (
                    "hash",
                    models.CharField(
                        help_text="SHA-256(整個 snapshot JSON)", max_length=64
                    ),
                ),
                (
                    "chain_tx_hash",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
