# Generated by Django 6.0.1 on 2026-03-21 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Covenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "covenant_id",
                    models.CharField(
                        help_text="格式：cvnt_{uuid_v4}", max_length=50, unique=True
                    ),
                ),
                ("version", models.CharField(default="ACP@1.0", max_length=20)),
                (
                    "space_type",
                    models.CharField(
                        choices=[
                            ("book", "書籍創作"),
                            ("code", "程式碼協作"),
                            ("music", "音樂創作"),
                            ("custom", "自定義"),
                        ],
                        default="book",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "language",
                    models.JSONField(
                        default=list, help_text="語言列表，例如 ['zh-TW', 'en']"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("OPEN", "開放加入"),
                            ("ACTIVE", "執行中"),
                            ("LOCKED", "已鎖定"),
                            ("SETTLED", "已結算"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("cover_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "owner_share_pct",
                    models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
                ),
                (
                    "platform_share_pct",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "contributor_pool_pct",
                    models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformIdentity",
            fields=[
                (
                    "platform_id",
                    models.CharField(
                        help_text="pid_{uuid_v4}",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("kyc_ref", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AccessTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tier_id", models.CharField(max_length=50)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "price_usd",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "token_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("max_slots", models.IntegerField(blank=True, null=True)),
                ("permissions", models.JSONField(default=list)),
                (
                    "covenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tiers",
                        to="covenants.covenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("covenant", "tier_id")},
            },
        ),
        migrations.CreateModel(
            name="CovenantMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_id",
                    models.CharField(help_text="agent_{random_8chars}", max_length=50),
                ),
                ("is_owner", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "covenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="covenants.covenant",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="covenants.accesstier",
                    ),
                ),
                (
                    "platform_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="covenants.platformidentity",
                    ),
                ),
            ],
            options={
                "unique_together": {("covenant", "agent_id")},
            },
        ),
    ]
