# Generated by Django 6.0.1 on 2026-03-21 10:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChainAnchor",
            fields=[
                (
                    "anchor_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("covenant_id", models.CharField(db_index=True, max_length=50)),
                ("anchor_type", models.CharField(max_length=50)),
                ("from_sequence", models.PositiveIntegerField()),
                ("to_sequence", models.PositiveIntegerField()),
                ("entry_count", models.PositiveIntegerField()),
                ("range_hash", models.CharField(max_length=64)),
                ("chain", models.CharField(default="base", max_length=20)),
                ("tx_hash", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("anchored_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("covenant_id", models.CharField(db_index=True, max_length=50)),
                ("sequence", models.PositiveIntegerField()),
                ("agent_id", models.CharField(max_length=50)),
                ("session_id", models.CharField(max_length=50)),
                ("tool_name", models.CharField(max_length=100)),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("clause", "Clause Tool"),
                            ("query", "Query Tool"),
                            ("admin", "Admin Tool"),
                        ],
                        max_length=20,
                    ),
                ),
                ("params_hash", models.CharField(max_length=64)),
                ("params_preview", models.JSONField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("rejected", "Rejected"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("result_detail", models.TextField(blank=True)),
                ("tokens_delta", models.IntegerField(default=0)),
                ("state_before", models.CharField(max_length=20)),
                ("state_after", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("prev_log_id", models.UUIDField(blank=True, null=True)),
                ("hash", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["covenant_id", "sequence"],
                "unique_together": {("covenant_id", "sequence")},
            },
        ),
    ]
